### ISSUE TITLE
Miscellaneous bugs

### ISSUE THREAD

**Issue by bwittenburg** [robertdebock/ansible-role-f5_ltm#3]
## Describe the bug
test if f5_ltm_provider is set correctly: 
  - in defaults/main.yml, server_port variable is defined but tasks/assert.yml actually checks for just port

test if item in f5_ltm_pool_members is set correctly:
  - in tasks/assert.yml, member should be members (plural)

test if item if f5_ltm_virtual_servers is set correctly:
  - in tasks/assert.yml, f5_ltm_virtual_servers evaluation is missing loop and loop control

typo error in tasks/main.yml (fixed):
  - in create pools task, ft_ltm_partition should be f5_ltm_partition

invalid evaluation in tasks/main.yml:
  - create pools checks for ft_ltm_partition | bool, should check if defined
 
invalid name in tasks/pool_members.yml:
  - multiple references to "pool_member", which is not defined. Added loop_var in tasks/main.yml in pool_member task
 
invalid variable in tasks/pool_members.yml:
  - variable 'provider' should be f5_ltm_provider

invalid variable in tasks/main.yml:
  - variable 'provider' should be f5_ltm_provider
 
## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: Create F5 LTM
  hosts: f5-big-ip
  vars:
    f5_ltm_partition: Common
    f5_ltm_nodes:
      - name: node01.internaldomain.com
        host: 10.10.10.11
      - name: node02.internaldomain.com
        host: 10.10.10.12
    f5_ltm_pools:
      - name: f5-ltm_pool
        lb_method: least-connections-member
        monitor_type: "and_list"
        monitors: /Common/https
    f5_ltm_pool_members:
      - name: f5-ltm_pool
        members:
          - name: node01.internaldomain.com
            port: 443
          - name: node02.internaldomain.com
            port: 443
    f5_ltm_virtual_servers:
      - name: f5-ltm_vs
        pool: f5-ltm_pool
        destination: 10.10.100.11
        port: 443
        enable_vlans: /Common/all
        all_profiles:
          - http
          - clientssl
        snat: automap
  gather_facts: False
  connection: local
  tasks:
    - include_role:
        name: f5_ltm
```

## Output

Show at least the error, possible related output, maybe just all the output.

## Environment

- Control node OS: Red Hat Enterprise Linux release 8.3 (Ootpa)
- Control node Ansible version: ansible 2.9.15
- Managed node OS: BIG-IP 14.1.2.6 Build 0.0.2 Point Release 6

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
